# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-20 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='category',
            name='declare',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='分类描述'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, help_text='可选，如若为空将摘取正文的前300个字符', max_length=300, null=True, verbose_name='摘要'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
