# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-20 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180520_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
    ]
